name: CI Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build the project
        run: echo "Building project..."

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ${{ github.workspace }}

      - name: Final Step
        run: echo "Final step of the workflow" && sleep 30
